# -*- coding: utf-8 -*-
"""solution/race_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJO2e5xzGY7mSDnXWBS3X_mDuIKSBD_G
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/SansaTechnologies/box-box-box.git
# %cd box-box-box

# create solution folder files
!mkdir -p solution
!touch solution/race_simulator.py
!touch solution/run_command.txt

with open("solution/run_command.txt", "w") as f:
    f.write("python solution/race_simulator.py")

code = r'''
import json
import sys

data = json.load(sys.stdin)

output = {
    "race_id": data["race_id"],
    "finishing_positions": []
}

print(json.dumps(output))
'''

with open("solution/race_simulator.py", "w") as f:
    f.write(code)

!python solution/race_simulator.py < data/test_cases/inputs/test_001.json

code = r'''
import json
import sys

data = json.load(sys.stdin)

strategies = data["strategies"]

driver_ids = []
for key in strategies:
    driver_ids.append(strategies[key]["driver_id"])

output = {
    "race_id": data["race_id"],
    "finishing_positions": driver_ids
}

print(json.dumps(output))
'''

with open("solution/race_simulator.py", "w") as f:
    f.write(code)

!python solution/race_simulator.py < data/test_cases/inputs/test_001.json

code = r'''
import json
import sys

data = json.load(sys.stdin)

race_config = data["race_config"]

base_lap_time = race_config["base_lap_time"]
total_laps = race_config["total_laps"]
pit_time = race_config["pit_lane_time"]
track_temp = race_config["track_temp"]

strategies = data["strategies"]

# just print to check
print(base_lap_time, total_laps, pit_time, track_temp)
'''

with open("solution/race_simulator.py", "w") as f:
    f.write(code)

!python solution/race_simulator.py < data/test_cases/inputs/test_001.json

code = r'''
import json
import sys

data = json.load(sys.stdin)

race_config = data["race_config"]
base_lap_time = race_config["base_lap_time"]
total_laps = race_config["total_laps"]
pit_time = race_config["pit_lane_time"]

strategies = data["strategies"]

driver_times = []

for key in strategies:
    driver_id = strategies[key]["driver_id"]
    pit_stops = strategies[key]["pit_stops"]

    num_pits = len(pit_stops)
    total_time = (total_laps * base_lap_time) + (num_pits * pit_time)

    driver_times.append((driver_id, total_time))

print(driver_times)
'''

with open("solution/race_simulator.py", "w") as f:
    f.write(code)

!python solution/race_simulator.py < data/test_cases/inputs/test_001.json

code = r'''
import json
import sys

data = json.load(sys.stdin)

race_config = data["race_config"]
base_lap_time = race_config["base_lap_time"]
total_laps = race_config["total_laps"]
pit_time = race_config["pit_lane_time"]

strategies = data["strategies"]

tire_offset = {
    "SOFT": -0.8,
    "MEDIUM": 0.0,
    "HARD": 0.8
}

driver_times = []

for key in strategies:
    driver = strategies[key]
    driver_id = driver["driver_id"]
    starting_tire = driver["starting_tire"]
    pit_stops = driver["pit_stops"]

    num_pits = len(pit_stops)
    lap_time = base_lap_time + tire_offset[starting_tire]
    total_time = (total_laps * lap_time) + (num_pits * pit_time)

    driver_times.append((driver_id, total_time))

print(driver_times)
'''

with open("solution/race_simulator.py", "w") as f:
    f.write(code)

!python solution/race_simulator.py < data/test_cases/inputs/test_001.json

data = __import__("json").load(open("data/test_cases/inputs/test_001.json"))

first_driver = data["strategies"]["pos1"]
print(first_driver)

data = __import__("json").load(open("data/test_cases/inputs/test_001.json"))

driver = data["strategies"]["pos1"]
total_laps = data["race_config"]["total_laps"]

starting_tire = driver["starting_tire"]
pit_stops = driver["pit_stops"]

current_tire = starting_tire
start_lap = 1
segments = []

for stop in pit_stops:
    pit_lap = stop["lap"]
    segments.append((start_lap, pit_lap, current_tire))
    current_tire = stop["to_tire"]
    start_lap = pit_lap + 1

segments.append((start_lap, total_laps, current_tire))

print(segments)

data = __import__("json").load(open("data/test_cases/inputs/test_001.json"))

driver = data["strategies"]["pos1"]
race_config = data["race_config"]

base_lap_time = race_config["base_lap_time"]
total_laps = race_config["total_laps"]
pit_time = race_config["pit_lane_time"]

tire_offset = {
    "SOFT": -0.8,
    "MEDIUM": 0.0,
    "HARD": 0.8
}

starting_tire = driver["starting_tire"]
pit_stops = driver["pit_stops"]

current_tire = starting_tire
start_lap = 1
segments = []

for stop in pit_stops:
    pit_lap = stop["lap"]
    segments.append((start_lap, pit_lap, current_tire))
    current_tire = stop["to_tire"]
    start_lap = pit_lap + 1

segments.append((start_lap, total_laps, current_tire))

total_time = 0.0

for seg_start, seg_end, tire in segments:
    laps_in_segment = seg_end - seg_start + 1
    lap_time = base_lap_time + tire_offset[tire]
    total_time += laps_in_segment * lap_time

total_time += len(pit_stops) * pit_time

print("segments =", segments)
print("total_time =", total_time)

code = r'''
import json
import sys

data = json.load(sys.stdin)

race_config = data["race_config"]
base_lap_time = race_config["base_lap_time"]
total_laps = race_config["total_laps"]
pit_time = race_config["pit_lane_time"]

strategies = data["strategies"]

tire_offset = {
    "SOFT": -0.8,
    "MEDIUM": 0.0,
    "HARD": 0.8
}

driver_times = []

for key in strategies:
    driver = strategies[key]
    driver_id = driver["driver_id"]
    starting_tire = driver["starting_tire"]
    pit_stops = driver["pit_stops"]

    current_tire = starting_tire
    start_lap = 1
    segments = []

    for stop in pit_stops:
        pit_lap = stop["lap"]
        segments.append((start_lap, pit_lap, current_tire))
        current_tire = stop["to_tire"]
        start_lap = pit_lap + 1

    segments.append((start_lap, total_laps, current_tire))

    total_time = 0.0

    for seg_start, seg_end, tire in segments:
        laps_in_segment = seg_end - seg_start + 1
        lap_time = base_lap_time + tire_offset[tire]
        total_time += laps_in_segment * lap_time

    total_time += len(pit_stops) * pit_time

    driver_times.append((driver_id, total_time))

print(driver_times)
'''

with open("solution/race_simulator.py", "w") as f:
    f.write(code)

!python solution/race_simulator.py < data/test_cases/inputs/test_001.json

code = r'''
import json
import sys

data = json.load(sys.stdin)

race_config = data["race_config"]
base_lap_time = race_config["base_lap_time"]
total_laps = race_config["total_laps"]
pit_time = race_config["pit_lane_time"]

strategies = data["strategies"]

tire_offset = {
    "SOFT": -0.8,
    "MEDIUM": 0.0,
    "HARD": 0.8
}

driver_times = []

for key in strategies:
    driver = strategies[key]
    driver_id = driver["driver_id"]
    starting_tire = driver["starting_tire"]
    pit_stops = driver["pit_stops"]

    current_tire = starting_tire
    start_lap = 1
    segments = []

    for stop in pit_stops:
        pit_lap = stop["lap"]
        segments.append((start_lap, pit_lap, current_tire))
        current_tire = stop["to_tire"]
        start_lap = pit_lap + 1

    segments.append((start_lap, total_laps, current_tire))

    total_time = 0.0

    for seg_start, seg_end, tire in segments:
        laps_in_segment = seg_end - seg_start + 1
        lap_time = base_lap_time + tire_offset[tire]
        total_time += laps_in_segment * lap_time

    total_time += len(pit_stops) * pit_time

    driver_times.append((driver_id, total_time))

# sort by smallest total time
driver_times.sort(key=lambda x: x[1])

finishing_positions = []
for driver_id, total_time in driver_times:
    finishing_positions.append(driver_id)

output = {
    "race_id": data["race_id"],
    "finishing_positions": finishing_positions
}

print(json.dumps(output))
'''

with open("solution/race_simulator.py", "w") as f:
    f.write(code)

!python solution/race_simulator.py < data/test_cases/inputs/test_001.json

!chmod +x test_runner.sh
!./test_runner.sh

import json

with open("data/test_cases/expected_outputs/test_001.json", "r") as f:
    correct = json.load(f)

print(correct)

code = r'''
import json
import sys

data = json.load(sys.stdin)

race_config = data["race_config"]
base_lap_time = race_config["base_lap_time"]
total_laps = race_config["total_laps"]
pit_time = race_config["pit_lane_time"]

strategies = data["strategies"]

tire_offset = {
    "SOFT": -0.8,
    "MEDIUM": 0.0,
    "HARD": 0.8
}

degradation = {
    "SOFT": 0.08,
    "MEDIUM": 0.05,
    "HARD": 0.03
}

driver_times = []

for key in strategies:
    driver = strategies[key]
    driver_id = driver["driver_id"]
    starting_tire = driver["starting_tire"]
    pit_stops = driver["pit_stops"]

    current_tire = starting_tire
    start_lap = 1
    segments = []

    for stop in pit_stops:
        pit_lap = stop["lap"]
        segments.append((start_lap, pit_lap, current_tire))
        current_tire = stop["to_tire"]
        start_lap = pit_lap + 1

    segments.append((start_lap, total_laps, current_tire))

    total_time = 0.0

    for seg_start, seg_end, tire in segments:
        laps_in_segment = seg_end - seg_start + 1

        for lap_on_tire in range(1, laps_in_segment + 1):
            lap_time = base_lap_time + tire_offset[tire] + (lap_on_tire - 1) * degradation[tire]
            total_time += lap_time

    total_time += len(pit_stops) * pit_time

    driver_times.append((driver_id, total_time))

driver_times.sort(key=lambda x: x[1])

finishing_positions = []
for driver_id, total_time in driver_times:
    finishing_positions.append(driver_id)

output = {
    "race_id": data["race_id"],
    "finishing_positions": finishing_positions
}

print(json.dumps(output))
'''

with open("solution/race_simulator.py", "w") as f:
    f.write(code)

!python solution/race_simulator.py < data/test_cases/inputs/test_001.json

code = r'''
import json
import sys

data = json.load(sys.stdin)

race_config = data["race_config"]
base_lap_time = race_config["base_lap_time"]
total_laps = race_config["total_laps"]
pit_time = race_config["pit_lane_time"]

strategies = data["strategies"]

tire_offset = {
    "SOFT": -0.8,
    "MEDIUM": 0.0,
    "HARD": 0.8
}

degradation = {
    "SOFT": 0.08,
    "MEDIUM": 0.05,
    "HARD": 0.03
}

grace_laps = {
    "SOFT": 3,
    "MEDIUM": 4,
    "HARD": 5
}

driver_times = []

for key in strategies:
    driver = strategies[key]
    driver_id = driver["driver_id"]
    starting_tire = driver["starting_tire"]
    pit_stops = driver["pit_stops"]

    current_tire = starting_tire
    start_lap = 1
    segments = []

    for stop in pit_stops:
        pit_lap = stop["lap"]
        segments.append((start_lap, pit_lap, current_tire))
        current_tire = stop["to_tire"]
        start_lap = pit_lap + 1

    segments.append((start_lap, total_laps, current_tire))

    total_time = 0.0

    for seg_start, seg_end, tire in segments:
        laps_in_segment = seg_end - seg_start + 1

        for lap_on_tire in range(1, laps_in_segment + 1):
            extra_wear_laps = max(0, lap_on_tire - grace_laps[tire])
            lap_time = base_lap_time + tire_offset[tire] + extra_wear_laps * degradation[tire]
            total_time += lap_time

    total_time += len(pit_stops) * pit_time
    driver_times.append((driver_id, total_time))

driver_times.sort(key=lambda x: x[1])

finishing_positions = [driver_id for driver_id, _ in driver_times]

output = {
    "race_id": data["race_id"],
    "finishing_positions": finishing_positions
}

print(json.dumps(output))
'''

with open("solution/race_simulator.py", "w") as f:
    f.write(code)

!python solution/race_simulator.py < data/test_cases/inputs/test_001.json

code = r'''
import json
import sys

data = json.load(sys.stdin)

race_config = data["race_config"]
base_lap_time = race_config["base_lap_time"]
total_laps = race_config["total_laps"]
pit_time = race_config["pit_lane_time"]
track_temp = race_config["track_temp"]

strategies = data["strategies"]

tire_offset = {
    "SOFT": -0.8,
    "MEDIUM": 0.0,
    "HARD": 0.8
}

degradation = {
    "SOFT": 0.08,
    "MEDIUM": 0.05,
    "HARD": 0.03
}

grace_laps = {
    "SOFT": 3,
    "MEDIUM": 4,
    "HARD": 5
}

temp_factor = 1 + ((track_temp - 30) * 0.02)

driver_times = []

for key in strategies:
    driver = strategies[key]
    driver_id = driver["driver_id"]
    starting_tire = driver["starting_tire"]
    pit_stops = driver["pit_stops"]

    current_tire = starting_tire
    start_lap = 1
    segments = []

    for stop in pit_stops:
        pit_lap = stop["lap"]
        segments.append((start_lap, pit_lap, current_tire))
        current_tire = stop["to_tire"]
        start_lap = pit_lap + 1

    segments.append((start_lap, total_laps, current_tire))

    total_time = 0.0

    for seg_start, seg_end, tire in segments:
        laps_in_segment = seg_end - seg_start + 1

        for lap_on_tire in range(1, laps_in_segment + 1):
            extra_wear_laps = max(0, lap_on_tire - grace_laps[tire])
            wear = extra_wear_laps * degradation[tire] * temp_factor
            lap_time = base_lap_time + tire_offset[tire] + wear
            total_time += lap_time

    total_time += len(pit_stops) * pit_time
    driver_times.append((driver_id, total_time))

driver_times.sort(key=lambda x: x[1])

finishing_positions = [driver_id for driver_id, _ in driver_times]

output = {
    "race_id": data["race_id"],
    "finishing_positions": finishing_positions
}

print(json.dumps(output))
'''

with open("solution/race_simulator.py", "w") as f:
    f.write(code)

!python solution/race_simulator.py < data/test_cases/inputs/test_001.json

import json

with open("data/test_cases/inputs/test_001.json", "r") as f:
    data = json.load(f)

for key, driver in data["strategies"].items():
    if driver["driver_id"] in ["D003", "D009", "D019"]:
        print(driver)

